// projects.js: every project in the game. Phase 2 projects carry phase: 2.
// A cost can be a number or a function (priced for where you are in the game).
const projectCost = (p) => (typeof p.cost === "function" ? p.cost() : p.cost);
// Phase 1 prices that grow with the model generation, capped at the phase 2 price.
const scaledCost = (k, full) => () => (S.phase === 2 ? full : Math.min(full, k * Math.pow(5, S.gen)));
// ---------- projects ----------
const PROJECTS = [
  { id: "dynprice", title: "Dynamic pricing", desc: "The price sets itself to wherever demand meets capacity.", cost: 250,
    when: () => S.gen >= 1, buy: () => {} },
  { id: "hands", title: "Remote hands", desc: "Someone at the colo swaps dead GPUs for you. Bills in 15-minute increments.", cost: 3000,
    when: () => S.gen >= 2 && S.fails > 0, buy: () => {} },
  { id: "autockpt", title: "Automatic checkpoint restarts", desc: "The run rolls itself back. You can finally sleep.", cost: 30000,
    when: () => S.gen >= 3 && S.spikes > 0, buy: () => {} },
  { id: "hac", title: "Hot-aisle containment", desc: "Plastic curtains, basically. 15 kW per rack. New leases only; older space needs a retrofit.", cost: 120,
    when: () => S.gpus >= 5 && S.cooling < 1, buy: () => { S.cooling = Math.max(S.cooling, 1); } },
  { id: "rdhx", title: "Rear-door heat exchangers", desc: "25 kW per rack. New leases only; older space needs a retrofit.", cost: 400,
    when: () => S.gen >= 1 && S.cooling < 2, buy: () => { S.cooling = Math.max(S.cooling, 2); } },
  { id: "modelcard", title: "Publish a model card", desc: "Transparency, briefly. +15 hype, and hype fades 25% slower from now on.", cost: 50,
    when: () => S.gen >= 1, buy: () => { S.hype += 15; } },
  { id: "evals", title: "Tune on the benchmark", desc: "Numbers went up. +35 hype, and every post can cite the benchmark: posts earn 50% more hype.", cost: 2000,
    when: () => S.gen >= 3, buy: () => { S.hype += 35; } },
  { id: "sales", title: "Enterprise sales team", desc: "They will find the demand. Demand x2.", cost: 20000,
    when: () => S.gen >= 3, buy: () => { S.demandMult *= 2; } },
  { id: "dlc", title: "Direct-to-chip liquid cooling", desc: "60 kW per rack. New leases only; older space needs a retrofit.", cost: 150000,
    when: () => S.gen >= 4 && S.cooling < 3, buy: () => { S.cooling = Math.max(S.cooling, 3); } },
  { id: "keynote", title: "Keynote: “the next one is the big one”", desc: "+50 hype. You now have fans: posts go viral twice as often, and the timeline tires of you half as fast.", cost: 200000,
    when: () => S.gen >= 4, buy: () => { S.hype += 50; } },
  { id: "water", title: "Pledge: water-positive by 2040", desc: "A pledge. It costs nothing today. +25 hype.", cost: 0,
    when: () => S.tier >= 3, buy: () => { S.hype += 25; } },
  { id: "immersion", title: "Immersion tanks", desc: "120 kW per rack. The GPUs go in the soup. New leases only; older space needs a retrofit.", cost: 5000000,
    when: () => S.gen >= 5 && S.cooling < 4, buy: () => { S.cooling = Math.max(S.cooling, 4); } },
  { id: "substation", title: "Pay for the substation", desc: "The landlord's power caps double. You paid for their upgrade.", cost: 15000000,
    when: () => S.gen >= 5 && S.tier >= 3, buy: () => { S.powerBoost = 2; } },
  { id: "twophase", title: "Two-phase immersion", desc: "200 kW per rack. The GPUs boil, on purpose. New leases only; older space needs a retrofit.", cost: 40000000,
    when: () => S.gen >= 6 && S.cooling < 5, buy: () => { S.cooling = Math.max(S.cooling, 5); } },
  { id: "synthdata", title: "Train on synthetic data", desc: "The model writes its own training data. What could go wrong. Training +50%.", cost: 2000000,
    when: () => S.gen >= 5, buy: () => {} },
  { id: "distill", title: "Distill a cheap tier", desc: "Same model, smaller, sold to everyone. Demand x2.", cost: 4000000,
    when: () => S.gen >= 5, buy: () => { S.demandMult *= 2; } },
  { id: "poach", title: "Poach a research team", desc: "Their equity vests in four years. Their loyalty vests never. Training +50%.", cost: 6000000,
    when: () => S.gen >= 5, buy: () => {} },
  { id: "sovereign", title: "Sovereign AI partnership", desc: "A country buys in. Demand x3.", cost: 3000000,
    when: () => S.gen >= 5, buy: () => { S.demandMult *= 3; } },
  { id: "cba", title: "Community benefits agreement", desc: "A new playground near the substation. +20 hype.", cost: 1000000,
    when: () => S.tier >= 4, buy: () => { S.hype += 20; } },
  { id: "ground", title: "Break ground on your own campus", desc: "You have outgrown every landlord in the county. Build your own.", cost: 60000000,
    when: () => S.gen >= 6,
    needs: () => [S.gen < 7 && "train Gen 7", usedKW() < GROUND_KW && `run ${fmt(GROUND_KW / 1000)} MW of GPUs (now ${fmt(usedKW() / 1000)} MW)`].filter(Boolean),
    buy: () => { endPhase(); } },
  { id: "depr6", phase: 2, title: "Extend the depreciation schedule to 6 years", cost: 0,
    desc: "Reported earnings jump. The GPUs are exactly as old as they were. +20 hype.",
    when: () => Object.keys(S.fleet).some((g) => +g < S.chipIdx && S.fleet[g] > 0), buy: () => { S.hype += 20; } },
  // ---- phase 2: an infrastructure company buys infrastructure-company things ----
  { id: "rebrand", phase: 2, title: "Rebrand as a neocloud", cost: 5e6, desc: "New logo, same GPUs. +30 hype.",
    when: () => !!S.p2 && (S.p2.round || 0) >= 1, buy: () => { S.hype += 30; } },   // after Series E
  { id: "resdesk", phase: 2, title: "Reserved pricing desk", cost: 25e6, desc: "Three people and a spreadsheet. New contracts pay 20% more up front.",
    when: () => S.p2.contractN >= 1, buy: () => {} },
  { id: "sales2", phase: 2, title: "Enterprise sales, again", cost: 40e6, desc: "They find labs you have never heard of. Offers arrive 30% more often.",
    when: () => S.p2.contractN >= 3, buy: () => {} },
  { id: "vp", phase: 2, title: "Hire an ex-hyperscaler VP", cost: 30e6, desc: "They bring their Rolodex and their opinions. Offers are 20% bigger.",
    when: () => (S.p2.round || 0) >= 1, buy: () => {} },
  { id: "sovereign2", phase: 2, title: "Sovereign cloud region", cost: 60e6, desc: "A flag on the building. Sovereign AI funds pay 30% more.",
    when: () => S.p2.contractN >= 5, buy: () => {} },
  { id: "partner", phase: 2, title: "Parallax preferred-partner status", cost: 60e6, desc: "A plaque and an allocation. New GPUs cost 10% less.",
    when: () => S.chipIdx > (S.p2.startChip ?? S.chipIdx), buy: () => {} },
  { id: "refurb", phase: 2, title: "Buy a refurb shop", cost: 50e6, desc: "Trade-ins now pay 40% instead of 25%. Parallax is not thrilled.",
    when: () => Object.keys(S.fleet).some((g) => +g < S.chipIdx && S.fleet[g] > 0), buy: () => {} },
  { id: "inference", phase: 2, title: "Inference-only tier", cost: 80e6, desc: "Old chips get a second life. Their on-demand floor doubles.",
    when: () => Object.keys(S.fleet).some((g) => +g < S.chipIdx && S.fleet[g] > 0), buy: () => {} },
  { id: "liquid", phase: 2, title: "Liquid-cooling standard", cost: 50e6, desc: "Every campus hall holds 75 MW instead of 50. The plumbers are thrilled.",
    when: () => doneBuilds("hall", Infinity) >= 2, buy: () => {} },
  { id: "prefab", phase: 2, title: "Prefab data halls", cost: 30e6, desc: "Shipped on trucks, bolted together. Halls build 40% faster.",
    when: () => S.p2.builds.some((b) => b.kind === "hall"), buy: () => {} },
  { id: "lawyer", phase: 2, title: "An interconnection lawyer", cost: 20e6, desc: "Bills in six-minute increments. The queue moves 30% faster.",
    when: () => S.p2.queueN > 0 || !!S.p2.queue, buy: () => {} },
  { id: "btm", phase: 2, title: "Behind-the-meter turbines", cost: 40e6, desc: "Skip the grid entirely. Turbines make 70 MW instead of 50.",
    when: () => S.p2.builds.filter((b) => b.kind === "turbine").length >= 2, buy: () => {} },
  { id: "nuclearppa", phase: 2, title: "Sign a nuclear PPA", cost: 500e6, desc: "A power purchase agreement with a plant that exists. +200 MW of grid.",
    when: () => isPublic(), buy: () => { S.p2.grid += 200; } },
  { id: "securitize", phase: 2, title: "Securitize the backlog", cost: 10e6, desc: "Bundle the contracts, sell the bundle. Debt draws 50% bigger.",
    when: () => backlogMW() >= 200, buy: () => {} },
  { id: "silicon", phase: 2, title: "Announce custom silicon", cost: 100e6, desc: "A render and a codename. Nothing ships. +50 hype.",
    when: () => isPublic(), buy: () => { S.hype += 50; } },
  { id: "pledge2", phase: 2, title: "Pledge: water-positive by 2045", cost: 0, desc: "The 2040 pledge, extended. +15 hype.",
    when: () => acresUsed() >= 400, buy: () => { S.hype += 15; } },
  { id: "robots", phase: 2, title: "Campus expansion robots", cost: 60e6,
    desc: "They pour concrete, set transformers and never unionize. Halls and turbines build themselves whenever you're short and have cash.",
    when: () => (S.p2.round || 0) >= 1, buy: () => { S.p2.robotsAt = 0; } },   // after Series E
  // ---- fires, any phase ----
  { id: "suppression", phase: 0, title: "Inert-gas fire suppression", cost: scaledCost(400, 2e6),
    desc: "It removes the oxygen from the room. Please leave the room first. Fires happen half as often.",
    when: () => firesOf().n >= 1, buy: () => {} },
  { id: "ups", phase: 0, title: "Replace the UPS batteries", cost: scaledCost(1000, 5e6),
    desc: "The old ones came from a crypto miner's garage sale. Fires are half as big.",
    when: () => firesOf().n >= 1, buy: () => {} },
  // ---- honesty costs hype (and lets froth down gently) ----
  { id: "benchmarks1", phase: 1, title: "Publish the real benchmark numbers", cost: 0, hype: 20,
    desc: "The numbers were lower. Customers trust you more than investors do. Demand x1.3.",
    when: () => S.gen >= 3, buy: () => { S.demandMult *= 1.3; } },
  { id: "benchmarks", phase: 2, title: "Publish your real benchmark numbers", cost: 0, hype: 20,
    desc: "Enterprise buyers read them twice. Contracts pay 10% more.", when: () => !!S.p2.county, buy: () => {} },
  { id: "disclosewater", phase: 2, title: "Disclose your water usage", cost: 0, hype: 15,
    desc: "The number is large. Regulators appreciate knowing it. Water allocation +20%.", when: () => !!S.p2.county, buy: () => {} },
  { id: "hallucinate", phase: 2, title: "Admit the model hallucinates, in the docs", cost: 0, hype: 15,
    desc: "Section 9.4, paragraph 3. Reality checks hit half as hard from now on.", when: () => !!S.p2.county, buy: () => {} },
  { id: "honestcall", phase: 2, title: "An honest earnings call", cost: 0, hype: 25,
    desc: "You said \u201cwe don't know\u201d twice. The stock swings less, and lockup only drops 7%.", when: () => isPublic(), buy: () => {} },
  { id: "paytaxes", phase: 2, title: "Pay your taxes", cost: 0, hype: 10,
    desc: "Analysts called it a surprising use of cash. The county sells you land 20% cheaper.", when: () => !!S.p2.county, buy: () => {} },
  { id: "opensource", phase: 2, title: "Open-source last year's model", cost: 0, hype: 10,
    desc: "PivotCloud rebrands it within the hour. Developers find you anyway. Offers arrive 20% more often.",
    when: () => !!S.p2.county, buy: () => {} },
  // ---- water and fire ----
  { id: "drycooling", phase: 2, title: "Dry cooling", cost: 60e6, desc: "Big fans instead of evaporation. Halls need half the water.",
    when: () => doneBuilds("hall", Infinity) >= 1, buy: () => {} },
  { id: "golfcourse", phase: 2, title: "Buy the golf course's water rights", cost: 30e6,
    desc: "It was exempt from the drought. It is not exempt from you. +2 MGD.", when: () => S.p2.drought != null, buy: () => {} },
  { id: "firecrew", phase: 0, title: "A 24/7 on-site fire crew", cost: scaledCost(2000, 10e6), desc: "They have their own chili cook-off. Fires are out in 1 minute instead of 2.",
    when: () => firesOf().n >= 1, buy: () => {} },
  { id: "secondshift", phase: 2, title: "Hire a second construction shift", cost: 20e6,
    desc: "Twice the crews, half the overtime. Builds wear people down half as fast.", when: () => !!S.p2.people && S.p2.people.v < 60, buy: () => {} },
  { id: "cba", phase: 2, title: "Community benefits agreement", cost: 25e6,
    desc: "A new library, a splash pad and a 40-page PDF. Opposition rises half as fast.", when: () => !!S.p2.town && S.p2.town.v >= 50, buy: () => {} },
  { id: "leakdetect", phase: 2, title: "Leak-detection rope under every manifold", cost: 8e6,
    desc: "It screams when wet, like the facilities team. Leaks are found in 30 s instead of 60.", when: () => leaksOf().n >= 1, buy: () => {} },
  { id: "driptrays", phase: 2, title: "Drip trays", cost: 15e6,
    desc: "A $40 idea in a $15M rollout. Leaks no longer kill GPUs.", when: () => leaksOf().n >= 1, buy: () => {} },
];
