// projects.js: every project in the game. Phase 2 projects carry phase: 2.
// ---------- projects ----------
const PROJECTS = [
  { id: "dynprice", title: "Dynamic pricing", desc: "The price sets itself to wherever demand meets capacity.", cost: 250,
    when: () => S.gen >= 1, buy: () => {} },
  { id: "hands", title: "Remote hands", desc: "Someone at the colo swaps dead GPUs for you. Bills in 15-minute increments.", cost: 3000,
    when: () => S.gen >= 2 && S.fails > 0, buy: () => {} },
  { id: "autockpt", title: "Automatic checkpoint restarts", desc: "The run rolls itself back. You can finally sleep.", cost: 30000,
    when: () => S.gen >= 3 && S.spikes > 0, buy: () => {} },
  { id: "hac", title: "Hot-aisle containment", desc: "Plastic curtains, basically. 15 kW per rack. New leases only; older space needs a retrofit.", cost: 120,
    when: () => S.gpus >= 5 && S.cooling < 1, buy: () => { S.cooling = Math.max(S.cooling, 1); } },
  { id: "rdhx", title: "Rear-door heat exchangers", desc: "25 kW per rack. New leases only; older space needs a retrofit.", cost: 400,
    when: () => S.gen >= 1 && S.cooling < 2, buy: () => { S.cooling = Math.max(S.cooling, 2); } },
  { id: "modelcard", title: "Publish a model card", desc: "Transparency, briefly. +15 hype, and hype fades 25% slower from now on.", cost: 50,
    when: () => S.gen >= 1, buy: () => { S.hype += 15; } },
  { id: "evals", title: "Tune on the benchmark", desc: "Numbers went up. +35 hype, and every post can cite the benchmark: posts earn 50% more hype.", cost: 2000,
    when: () => S.gen >= 3, buy: () => { S.hype += 35; } },
  { id: "sales", title: "Enterprise sales team", desc: "They will find the demand. Demand x2.", cost: 20000,
    when: () => S.gen >= 3, buy: () => { S.demandMult *= 2; } },
  { id: "dlc", title: "Direct-to-chip liquid cooling", desc: "60 kW per rack. New leases only; older space needs a retrofit.", cost: 150000,
    when: () => S.gen >= 4 && S.cooling < 3, buy: () => { S.cooling = Math.max(S.cooling, 3); } },
  { id: "keynote", title: "Keynote: “the next one is the big one”", desc: "+50 hype. You now have fans: posts go viral twice as often, and the timeline tires of you half as fast.", cost: 200000,
    when: () => S.gen >= 4, buy: () => { S.hype += 50; } },
  { id: "water", title: "Pledge: water-positive by 2040", desc: "A pledge. It costs nothing today. +25 hype.", cost: 0,
    when: () => S.tier >= 3, buy: () => { S.hype += 25; } },
  { id: "immersion", title: "Immersion tanks", desc: "120 kW per rack. The GPUs go in the soup. New leases only; older space needs a retrofit.", cost: 5000000,
    when: () => S.gen >= 5 && S.cooling < 4, buy: () => { S.cooling = Math.max(S.cooling, 4); } },
  { id: "substation", title: "Pay for the substation", desc: "The landlord's power caps double. You paid for their upgrade.", cost: 15000000,
    when: () => S.gen >= 5 && S.tier >= 3, buy: () => { S.powerBoost = 2; } },
  { id: "twophase", title: "Two-phase immersion", desc: "200 kW per rack. The GPUs boil, on purpose. New leases only; older space needs a retrofit.", cost: 40000000,
    when: () => S.gen >= 6 && S.cooling < 5, buy: () => { S.cooling = Math.max(S.cooling, 5); } },
  { id: "synthdata", title: "Train on synthetic data", desc: "The model writes its own training data. What could go wrong. Training +50%.", cost: 2000000,
    when: () => S.gen >= 5, buy: () => {} },
  { id: "distill", title: "Distill a cheap tier", desc: "Same model, smaller, sold to everyone. Demand x2.", cost: 4000000,
    when: () => S.gen >= 5, buy: () => { S.demandMult *= 2; } },
  { id: "poach", title: "Poach a research team", desc: "Their equity vests in four years. Their loyalty vests never. Training +50%.", cost: 6000000,
    when: () => S.gen >= 5, buy: () => {} },
  { id: "sovereign", title: "Sovereign AI partnership", desc: "A country buys in. Demand x3.", cost: 3000000,
    when: () => S.gen >= 5, buy: () => { S.demandMult *= 3; } },
  { id: "cba", title: "Community benefits agreement", desc: "A new playground near the substation. +20 hype.", cost: 1000000,
    when: () => S.tier >= 4, buy: () => { S.hype += 20; } },
  { id: "ground", title: "Break ground on your own campus", desc: "You have outgrown every landlord in the county. Build your own.", cost: 60000000,
    when: () => S.gen >= 6,
    needs: () => [S.gen < 7 && "train Gen 7", usedKW() < GROUND_KW && `run ${fmt(GROUND_KW / 1000)} MW of GPUs (now ${fmt(usedKW() / 1000)} MW)`].filter(Boolean),
    buy: () => { endPhase(); } },
  { id: "depr6", phase: 2, title: "Extend the depreciation schedule to 6 years", cost: 0,
    desc: "Reported earnings jump. The GPUs are exactly as old as they were. +20 hype.",
    when: () => Object.keys(S.fleet).some((g) => +g < S.chipIdx && S.fleet[g] > 0), buy: () => { S.hype += 20; } },
];
